import { IconBone, IconLeaf, IconSparkles } from "@tabler/icons-react";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { Button, Eyebrow } from "@/components/ui";
import { getProducts, optionalProductFields } from "@/lib/products";

export const dynamic = "force-dynamic";
const groups = { benefits: ["Product Benefits", "Special Ingredients", "Animal Food Nutrient Content Claim"], use: ["Recommended Uses For Product", "Specific Uses For Product", "Target Species", "Pet Type", "Breed Recommendation", "Dog Breed Size", "Age Range Description"], features: ["Additional Features", "Brand Name", "Flavor", "Item Form", "Container Type", "Animal Food Ingredient Claim", "Animal Food Diet Type", "Item Shape", "UPC", "Manufacturer", "ASIN"] };

export default async function ProductDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const product = (await getProducts()).find((item) => item.slug === slug); if (!product) notFound();
  const fields = optionalProductFields(product); const grouped = (labels: string[]) => fields.filter(([label]) => labels.includes(label));
  const facts = (items: [string, string][], Icon: typeof IconBone) => <div className="product-detail__facts">{items.map(([label, value]) => <div className="product-detail__fact" key={label}><Icon size={18} stroke={1.7} aria-hidden="true" /><strong>{label}</strong><span>{value}</span></div>)}</div>;
  return <main className="inner-page shell"><Breadcrumbs current={product.name} /><div className="product-detail"><div className="product-detail__visual">{product.imageUrl ? <img src={product.imageUrl} alt={product.name} /> : <div className="chew-illustration"><span>KHICHCHA</span></div>}</div><div><Eyebrow>{product.size} size dog chew</Eyebrow><h1>{product.name}</h1><p className="inner-page__intro">{product.description}</p>{product.details && <p className="product-detail__info">{product.details}</p>}<p className="product-detail__info">Always supervise your dog while chewing. This product is for animal consumption only.</p><Button className="product-detail__amazon" href={product.amazonUrl} external>Buy on Amazon ↗</Button></div></div><section className="product-detail-section product-detail-section--benefits"><div className="product-detail-section__copy"><Eyebrow>Product benefits</Eyebrow><h2>Why dogs love it</h2>{facts(grouped(groups.benefits), IconBone)}</div></section><section className="product-detail-section product-detail-section--use"><div className="product-detail-section__copy"><Eyebrow>Recommended use</Eyebrow><h2>Made for a slower chew</h2>{facts(grouped(groups.use), IconLeaf)}</div></section><section className="product-detail-section product-detail-section--features"><div className="product-detail-section__copy"><Eyebrow>Additional features</Eyebrow><h2>Thoughtful by design</h2>{facts(grouped(groups.features), IconSparkles)}</div></section><section className="product-specs"><Eyebrow>Product information</Eyebrow><div className="product-specs__table">{fields.map(([label, value]) => <div className="product-spec" key={label}><strong>{label}</strong><span>{value}</span></div>)}</div></section></main>;
}
